module.exports = {
    STATUS_CODES: {
      SUCCESS: 200,
      CREATED: 201,
      UNAUTHORIZED: 401,
      NOT_FOUND: 404,
      CONFLICT: 409,
      BAD_REQUEST: 400,
      INTERNAL_SERVER_ERROR: 500,
      UNPROCESSABLE_ENTITY: 422
    },
    TEXTS: {
      LOC_EXIST: "User has already subrscribed valid LOC!",
      CREATED: "Record created successfully!",
      UPDATED: "Record updated successfully!",
      DELETED: "Record deleted successfully!",
      FOUND: "Record found successfully!",
      SETTINGS_FOUND: "Settings found successfully!",
      NOT_FOUND: "Record not found!",
      CONFLICT: "Record already exist!",
      LOGIN: "Login Successfully!",
      INVALID_CREDENTIALS: "Invalid credentials!",
      OTP_SENT: "Otp sent Successfully!",
      OTP_VERIFIED: "Otp verified Successfully!",
      INVALID_OTP: "Invalid Otp",
      INVALID_AUTH_TOKEN: "Invalid auth token!",
      NO_AUTH_GIVEN: "No auth given",
      UN_AUTHORIZED: "Unauthorized access",
      EMAIL_VERIFIED: "Email verified!",
      PAYMENT_DONE: "Payment Done successfully!",
      EMAIL_NOT_VERIFIED: "Your email is not verified please check your email and verify it",
      Number_NOT_VERIFIED: "Please verify your phone number!",
      PASSWORD_RESET: "Password reset successfully!",
      OLD_PASSWORD: "You can not use old password",
      VERIFIED: "User is verified!",
      NOT_VERIFIED: "User not verified!",
      USER_NOT_FOUND: "User not found!",
      USER_EXIST: "User already exist!",
      USER_ATHLETE: "User is already athlete!",
      APPVOVED_REQUEST: "Request Approved",
      REJECTED_REQUEST: "Request Rejected",
      PENDING_REQUEST: "Request Pending",
      DATA_FOUND: "Data found",
      PASSWORD_UPDATED : "Password Updated Successfully",
      PROFILE_UPDATED : "Profile Updated",
      UPDATE_FAILED : "Update failed"
    },
  };